In [2]:
import numpy as np
import pandas as pd
len(dir(pd))

141

In [6]:
#series: It creates ony one column(1D)date
import numpy as np
import pandas as pd
a= np.array([10,20,30,40])
b = pd.Series(a)
b

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
b[2]

np.int64(30)

In [8]:
a= {'customer':['rahul','priya','arjun','sneha'],
    'product':['laptop','mobile','headset','tablet'],
    'quantity':[1,2,3,1],
    'price':[55000,18000,2000,25000],
    'totalamount':[55000,36000,6000,25000]
    }
b= pd.DataFrame(a)
b

  customer  product  quantity  price  totalamount
0    rahul   laptop         1  55000        55000
1    priya   mobile         2  18000        36000
2    arjun  headset         3   2000         6000
3    sneha   tablet         1  25000        25000

In [15]:
b['customer'][2]

/tmp/ipykernel_3634/625608957.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b['customer'][2]

   customer  product  quantity  price  totalamount
r1    rahul   laptop         1  55000        55000
r2    priya   mobile         2  18000        36000
r3    arjun  headset         3   2000         6000
r4    sneha   tablet         1  25000        25000

In [9]:
b=pd.DataFrame(a,index=['r1','r2','r3','r4'])

   customer  product  quantity  price  totalamount
r1    rahul   laptop         1  55000        55000
r2    priya   mobile         2  18000        36000
r3    arjun  headset         3   2000         6000
r4    sneha   tablet         1  25000        25000

In [16]:
b['product']['r1':'r3']

r1     laptop
r2     mobile
r3    headset
Name: product, dtype: object

In [17]:
b['product']['r2':]

r2     mobile
r3    headset
r4     tablet
Name: product, dtype: object

In [18]:
b.loc['r1':'r3','customer':'quantity']

   customer  product  quantity
r1    rahul   laptop         1
r2    priya   mobile         2
r3    arjun  headset         3

In [19]:
b.iloc[1:3,2:4]

    quantity  price
r2         2  18000
r3         3   2000

In [21]:
len(b.columns)

5

In [25]:
import warnings
warnings.filterwarnings("ignore")
b['customer']['r1']='anu'
b

   customer  product  quantity  price  totalamount
r1      anu   laptop         1  55000        55000
r2    priya   mobile         2  18000        36000
r3    arjun  headset         3   2000         6000
r4    sneha   tablet         1  25000        25000

In [37]:
b['tax']=[12,13,14,15]
b

   customer  product  quantity  price  totalamount  tax
r1      anu   laptop         1  55000        55000   12
r2    priya   mobile         2  18000        36000   13
r3    arjun  headset         3   2000         6000   14
r4    sneha   tablet         1  25000        25000   15

KeyError: "['customer'] not found in axis"

In [27]:
f='india'
e=f.capitalize()
e

'India'

In [53]:
b= b.drop(['r4'],axis=0)
b

   customer product  quantity  price  totalamount    EMI
r1      anu  laptop         1  55000        55000  300.0
r2    priya  mobile         2  18000        36000    NaN

In [43]:
b=b.rename(columns={'tax':'EMI'})
b

   customer  product  quantity  price  totalamount  EMI
r1      anu   laptop         1  55000        55000   12
r2    priya   mobile         2  18000        36000   13
r3    arjun  headset         3   2000         6000   14
r4    sneha   tablet         1  25000        25000   15

In [52]:
b['EMI']=[300,np.nan,400]
b

   customer product  quantity  price  totalamount    EMI
r1      anu  laptop         1  55000        55000  300.0
r2    priya  mobile         2  18000        36000    NaN
r4    sneha  tablet         1  25000        25000  400.0

In [54]:
b.to_csv("sample_data_of_pandas.csv",index=False)

In [58]:
b['EMI']=b['EMI'].fillna(100)
b

   customer product  quantity  price  totalamount    EMI
r1      anu  laptop         1  55000        55000  300.0
r2    priya  mobile         2  18000        36000  100.0

In [60]:
import numpy as np
import pandas as pd
df= pd.read_csv("/content/titanic.csv")
df
df.shape

(891, 12)

In [61]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [63]:
df.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [65]:
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
436,437,0,3,"Ford, Miss. Doolina Margaret ""Daisy""",female,21.0,2,2,W./C. 6608,34.375,NaN,S
402,403,0,3,"Jussila, Miss. Mari Aina",female,21.0,1,0,4137,9.825,NaN,S
634,635,0,3,"Skoog, Miss. Mabel",female,9.0,3,2,347088,27.900,NaN,S

In [74]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [93]:
t = pd.RangeIndex(10,50,2)

In [94]:
t

RangeIndex(start=10, stop=50, step=2)

In [95]:
for i in t:
  print(t)

RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)
RangeIndex(start=10, stop=50, step=2)

In [91]:
for i in df.index:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890

In [97]:
f = pd.DataFrame({"age":[10,20,30,40]})
f.index = pd.RangeIndex(21,25,1)
f

    age
21   10
22   20
23   30
24   40

In [99]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [100]:
df=df.dropna()

In [101]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [104]:
df['Sex'].unique()

array(['female', 'male'], dtype=object)

In [106]:
df['Sex'].value_counts()

Sex
male      95
female    88
Name: count, dtype: int64

In [111]:
t=pd.DataFrame({'animal':['lion','tiger','lion','tiger','lion','tiger'],'speed':[100,200,300,400,500,600]})
t

  animal  speed
0   lion    100
1  tiger    200
2   lion    300
3  tiger    400
4   lion    500
5  tiger    600

In [112]:
t.groupby(['animal']).mean()

        speed
animal
lion    300.0
tiger   400.0

In [116]:
df.to_csv("bhj.csv",index=False)

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [119]:
h=df.select_dtypes(exclude='object')
h

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
1              2         1       1  38.0      1      0  71.2833
3              4         1       1  35.0      1      0  53.1000
6              7         0       1  54.0      0      0  51.8625
10            11         1       3   4.0      1      1  16.7000
11            12         1       1  58.0      0      0  26.5500
..           ...       ...     ...   ...    ...    ...      ...
871          872         1       1  47.0      1      1  52.5542
872          873         0       1  33.0      0      0   5.0000
879          880         1       1  56.0      0      1  83.1583
887          888         1       1  19.0      0      0  30.0000
889          890         1       1  26.0      0      0  30.0000

[183 rows x 7 columns]

In [120]:
j=pd.DataFrame({"age":[10,20,30],'name':['anu','tanu','manu']})
j

   age  name
0   10   anu
1   20  tanu
2   30  manu

In [122]:
d=pd.DataFrame({"age":[99,44,55],'name':['ff','gg','hh']})
d

   age name
0   99   ff
1   44   gg
2   55   hh

In [124]:
final_data=pd.concat([j,d],axis=0)
final_data

   age  name
0   10   anu
1   20  tanu
2   30  manu
0   99    ff
1   44    gg
2   55    hh